/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class binding_CalculatorNative */

#ifndef _Included_binding_CalculatorNative
#define _Included_binding_CalculatorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     binding_CalculatorNative
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_binding_CalculatorNative_create
  (JNIEnv *, jclass);

/*
 * Class:     binding_CalculatorNative
 * Method:    destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_binding_CalculatorNative_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     binding_CalculatorNative
 * Method:    add
 * Signature: (JIILbinding/refs/IntRef;)I
 */
JNIEXPORT jint JNICALL Java_binding_CalculatorNative_add
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     binding_CalculatorNative
 * Method:    sub
 * Signature: (JIILbinding/refs/IntRef;)I
 */
JNIEXPORT jint JNICALL Java_binding_CalculatorNative_sub
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     binding_CalculatorNative
 * Method:    cntOpsDone
 * Signature: (JLbinding/refs/IntRef;)I
 */
JNIEXPORT jint JNICALL Java_binding_CalculatorNative_cntOpsDone
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     binding_CalculatorNative
 * Method:    resetCounter
 * Signature: (JLbinding/refs/IntRef;)I
 */
JNIEXPORT jint JNICALL Java_binding_CalculatorNative_resetCounter
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
